#! /bin/sh

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
./.config/bspwm/autostart &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^2'

