export EDITOR="nvim"
export TERMINAL="alacritty"
export FILEMANAGER="nemo"
export BROWSER="brave"
export rofi_theme="~/.themes/rofi/dark.rasi"
export PATH="$PATH:$HOME/scripts:$HOME/AppImages:$HOME/.cargo/bin"
