#!/usr/bin/env bash

set -e

cd ~/

TARGET_DIR="/media/$USER/backup"
OUTPUT_FILE="dev-backup-$(date +%Y-%m-%d-%I:%M).tar.gz"

if [ -n "$1" ]; then
    TARGET_DIR="$1"
fi

# If `TARGET_DIR` does not exists default to $HOME
if [ ! -d "$TARGET_DIR" ]; then
    TARGET_DIR=$HOME
fi

tar --exclude="target" --exclude="node_modules" \
    -vzpcf "$TARGET_DIR/$OUTPUT_FILE" dev

