#!/usr/bin/env bash

DIRS="$(fd \
    --prune \
    -t d \
    -I '^target$|^node_modules$' \
    ~/dev/)"

# shellcheck disable=SC2312
DIRS_SELECTED="$(echo "${DIRS}" | xargs du -hs \
    | fzf \
    --multi \
    --reverse \
    --bind "ctrl-a:select-all")"

DIRS_TO_REMOVE="$(echo "${DIRS_SELECTED}" | cut -f 2)"

if [[ -z "${DIRS_TO_REMOVE}" ]]
then
    echo "Nothing was selected."
    exit 0
fi

echo "${DIRS_TO_REMOVE}"
read -r -p "Are you sure? [y/N] " confirm

if [[ "${confirm}"  =~ ^(yes|y)$ ]]; then
    echo "${DIRS_TO_REMOVE}"
    # rm -rf ${DIRS_TO_REMOVE}
fi

