#!/usr/bin/env bash

DIRS="$(fd \
    --prune \
    -t d \
    -I '^target$|^node_modules$' \
    ~/dev/ \
    | fzf \
    --multi \
    --reverse \
    --bind "ctrl-a:select-all" \
    )"

if [[ -z "${DIRS}" ]]
then
    echo "Nothing was selected."
    exit 0
fi

echo "${DIRS}"
read -r -p "Are you sure? [y/N] " confirm

if [[ "${confirm}"  =~ ^(yes|y)$ ]]
then
    rm -rf ${DIRS}
fi

