#!/bin/env bash

# easy edit

# NOTE: I don't know if the usage of 'entry' and 'entries' is correct here!

entries=(
    "$HOME/.todo"
    "$HOME/.dotfiles/"
    "$HOME/projects/rust/todo/"
    )

selected_entry=$(echo "${entries[@]}" | tr ' ' '\n' | dmenu -p "Select a file/dir" -l 30)

# check if entry exists
if [[ ! -e $selected_entry ]]; then
    notify-send "$selected_entry" "is not found"
    exit 0
fi

$TERMINAL -e "$EDITOR" "$selected_entry"
