#!/bin/sh

clang-format -style="{
    BasedOnStyle: Microsoft,
    AlignArrayOfStructures: Left,
    AlignConsecutiveAssignments: Consecutive,
    AlignConsecutiveMacros: Consecutive,
    AlignTrailingComments: true,
    AlignAfterOpenBracket: BlockIndent,
    BinPackArguments: false,
    BinPackParameters: false,
    ColumnLimit: 80,
    IndentCaseBlocks: true,
    IndentCaseLabels: true,
}" -dump-config > .clang-format

