#!/usr/bin/env bash

CONFIG_DIR="${HOME}/.config"

list=(
    "${CONFIG_DIR}/nvim/"
    "${CONFIG_DIR}/awesome/"
    "${HOME}/scripts/"
)

PROJECTS="$(fd -t d -d 2 --min-depth 2 . ~/dev)"
list+=("${PROJECTS}")

SOURCES="$(fd -t d -d 1 . ~/sources)"
list+=("${SOURCES}")

DIR="$(printf "%s\n" "${list[@]}" | rofi -dmenu)"

# check if $DIR is not empty string
if [[ -n "${DIR}" ]]; then
    if [[ -f "${DIR}/.tmuxinator.yml" ]]; then
        alacritty --working-directory "${DIR}" -e tmuxinator start
    else
        alacritty --working-directory "${DIR}" -e tmux new-session -s "$(basename "${DIR}")"
    fi
fi
