#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers/"
CURRENT_WALL=$(hyprctl hyprpaper listloaded)

# Get a random wallpaper that is not the current one
WALLPAPER=$(find "${WALLPAPER_DIR}"  -type f ! -name "$(basename "${CURRENT_WALL}")" | shuf -n 1)


# Apply the selected wallpaper
for mointor in $(hyprctl monitors -j | jq -r ".[] | .name"); do
    hyprctl hyprpaper reload "${mointor},${WALLPAPER}"
    sleep 0.1
done
