#!/bin/bash

URI=$(yad --entry --entry-label="Enter URI" --center --width=600)

dbus-send --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri string:$URI
