#!/usr/bin/env bash

SESSIONS_LIST="$(tmux list-sessions)"
SELECTED="$(echo "${SESSIONS_LIST}" | rofi -dmenu)"
SESSION="$(echo "${SELECTED}" | awk -F: '{printf $1}')"

if [[ -n "${SESSION}" ]]; then
    if [[ -t 0 ]]; then
        tmux attach -t "${SESSION}"
    else
        alacritty -e tmux attach -t "${SESSION}"
    fi
fi
