preload = /home/mesa/Pictures/wallpapers/Other/there_is_a_woman_standing_in_a_field_with_a_cloud_in_the_bac_8c692a506.png
#if more than one preload is desired then continue to preload other backgrounds
# preload = /path/to/next_image.png
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = ,/home/mesa/Pictures/wallpapers/Other/there_is_a_woman_standing_in_a_field_with_a_cloud_in_the_bac_8c692a506.png
#if more than one monitor in use, can load a 2nd image
# wallpaper = HDMI-A-1,/home/mesa/Pictures/wallpapers/characters/149.jpg
# .. more monitors

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
