#!/usr/bin/env bash

./.config/polybar/launch.sh --senpai-1 &

run() { killall $1; $1 & }

# ~/.fehbg &

run "picom"
run "deadd-notification-center"
run "xbindkeys"
run "btops"
run "imwheel -b 45"
run "flameshot"

killall mudae_reminder; ~/scripts/./mudae_reminder &
