#! /bin/bash

~/.config/bspwm/./autostart
~/.config/polybar/./launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config focused_border_color "#E84F4F"
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 30
#bspc config window_gap 15
bspc config window_gap 0

bspc rule -a discord desktop='^9'
bspc rule -a spotify desktop='^9'
bspc rule -a Steam desktop='^7'
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a nitrogen state=floating
bspc rule -a Eog state=floating
bspc rule -a Nsxiv state=floating
bspc rule -a gnome-calculator state=floating
