#! /bin/bash

~/scripts/./autostart

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 30
bspc config window_gap 15

bspc rule -a discord desktop='^2'
bspc rule -a feh state=floating
bspc rule -a mpv state=floating

