#! /bin/bash

gap=10
gaps=true

#killall sxhkd
#pgrep -x sxhkd > /dev/null || sxhkd &
~/scripts/./autostart

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1 
bspc config window_gap 0 
#bspc config window_gap $gap 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

if [[ "$gaps" = true ]]; then
  bspc config top_padding $((30+gap))
  bspc config left_padding $gap
  bspc config right_padding $gap
  bspc config bottom_padding $gap
  else
    bspc config top_padding 30
    bspc config left_padding 0
    bspc config right_padding 0
    bspc config bottom_padding 0
fi

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^2'
bspc rule -a feh state=floating
bspc rule -a mpv state=floating

